/**
 * This class is generated by jOOQ
 */
package com.github.sourcecase.jooqwithdocker.codegen;


import com.github.sourcecase.jooqwithdocker.codegen.tables.Author;
import com.github.sourcecase.jooqwithdocker.codegen.tables.Book;
import com.github.sourcecase.jooqwithdocker.codegen.tables.BookStore;
import com.github.sourcecase.jooqwithdocker.codegen.tables.BookToBookStore;
import com.github.sourcecase.jooqwithdocker.codegen.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.github.sourcecase.jooqwithdocker.codegen.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = com.github.sourcecase.jooqwithdocker.codegen.tables.Book.BOOK;

    /**
     * The table <code>library.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.github.sourcecase.jooqwithdocker.codegen.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>library.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.github.sourcecase.jooqwithdocker.codegen.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>library.language</code>.
     */
    public static final Language LANGUAGE = com.github.sourcecase.jooqwithdocker.codegen.tables.Language.LANGUAGE;
}
